### ISSUE TITLE
Import a local file deck JSON not working

### ISSUE THREAD

**Issue by heaven2k4** [ronelm2000/wsmtools#11]
So I tried to import the example JSON after trying to make my own, and it is throwing me an error.
![image](https://user-images.githubusercontent.com/64512135/87259194-bb853900-c466-11ea-99c8-34a0259b5a5b.png)

**Comment by ronelm2000** [comment]
The documentation is wrong (wow I'm stupid). To be fixed for the release notes.

The correct CLI is:
```
./wstools export /path/to/deck.json
./wstools export encoredecks_url --exporter local
```

Thanks for that; I totally missed it.

**Comment by ronelm2000** [comment]
Additionally I'll open a new card for documentation of the other features.
