### ISSUE TITLE
Can't Export Decks

### ISSUE THREAD

**Issue by Xnodox** [ronelm2000/wsmtools#14]
I currently cannot export decks from encore due to the error in the image attached. It was working for several days prior to the incident.
![2020-08-06 15_01_47-Select Windows PowerShell](https://user-images.githubusercontent.com/11744618/89641237-de90e600-d876-11ea-99b4-7687283242b6.png)

**Comment by ronelm2000** [comment]
That is a really wierd error. I'll take a look at it, but the fact that I can't even replicate this error makes it difficult to fix.

Can you try one of the latest CI builds over at Actions?

**Comment by Xnodox** [comment]
Thank you sir that fixed my issue
