### ISSUE TITLE
Kancolle 5th phase missing en translations even with successful parsing 

### ISSUE THREAD

**Issue by Patchoulidaze** [ronelm2000/wsmtools#17]
![wstools error](https://user-images.githubusercontent.com/64533377/92556600-f657f180-f29c-11ea-813f-1e55ca8109a0.PNG)
Tried parsing twice from HOTC but wstools claimed there's no translation even though the parse was successful

**Comment by ronelm2000** [comment]
Thanks for that, I'll check it out and see what I can do.

**Comment by Patchoulidaze** [comment]
an update, this is also affecting date a live set as well, even though I had no issues with it yesterda

**Comment by ronelm2000** [comment]
Sorry for the wait I was busy with the r4utools project.
Please export Weiss/Schwarz Promos first and see if the problems persist.
For now, I've added additional warnings if there are untranslated PRs, but this should work even with the latest stable version.
