### ISSUE TITLE
An assembly specified in the application dependencies manifest (wstools.deps.json) was not found

### ISSUE THREAD

**Issue by BryanTsy** [ronelm2000/wsmtools#24]
![128718580_677176346315200_151383145247706551_n](https://user-images.githubusercontent.com/37129646/100962896-3fe46f80-3560-11eb-9242-165b2872365b.jpg)

**Comment by ronelm2000** [comment]
Try clearing your Temporary Files folder and retry.

**Comment by BryanTsy** [comment]
thanks, it really works!

**Comment by ronelm2000** [comment]
I'll tag this as the official fix for this particular issue.
