### ISSUE TITLE
How to fix this error

### ISSUE THREAD

**Issue by ChunSquare** [ronelm2000/wsmtools#28]
Error:
  An assembly specified in the application dependencies manifest (wstools.deps.json) was not found:
    package: 'Microsoft.DotNet.PlatformAbstractions', version: '3.1.6'
    path: 'lib/netstandard2.0/Microsoft.DotNet.PlatformAbstractions.dll'

**Comment by ronelm2000** [comment]
Try clearing all Temporary Files and retry. This is an issue caused by libraries sometimes getting corrupted due to how .NET applications work, and is unfixable except by using AOT compilation.

**Comment by ChunSquare** [comment]
Where is the temporary files stored?

**Comment by ronelm2000** [comment]
It depends on your specific configuration. If you just want to delete them all, go to Disk Cleanup.
![image](https://user-images.githubusercontent.com/12634987/104836904-0f784b00-58ec-11eb-8c29-d99bfbaad76c.png)
![image](https://user-images.githubusercontent.com/12634987/104836910-1ef79400-58ec-11eb-8f7f-1897c83dab00.png)

**Comment by ChunSquare** [comment]
I deleted the temporary files and the error still pop up

**Comment by ChunSquare** [comment]
Ok thank you i have fixed the problem
