### ISSUE TITLE
wstools does not generate any files

### ISSUE THREAD

**Issue by TheDJAB** [ronelm2000/wsmtools#33]
Hello! 
I tried to import an english deck from encoredecks with the help of IanTCGs instructions. Powershell seemed to download the image files and card text, but then seemed to fail to safe it to the export folder. I'm unsure if it is a mistake on my part or if the program is doing something funny, since I don't know anything about coding. You'll find the code in the text file.
[Code_WS_Export.txt](https://github.com/ronelm2000/wsmtools/files/5897719/Code_WS_Export.txt)

**Comment by ronelm2000** [comment]
I'll look into this, but first, did you try creating an empty Export folder, or does the Export folder already exist in the first place? It seems that wsmtools itself was denied access to save the jpg file, so I'm not sure what the solution will have to entail...

**Comment by TheDJAB** [comment]
wstools created the folder on its own. Should delete the folder and create a new one?

**Comment by ronelm2000** [comment]
That's so wierd. Try opening your PowerShell console as admin and retry.

**Comment by TheDJAB** [comment]
That worked, thank you!
