### ISSUE TITLE
"Unhandled exception... ... Sequence contains no elements" error from certain Key 20th Anniversary cards

### ISSUE THREAD

**Issue by ShoukakusHusband** [ronelm2000/wsmtools#34]
Hi.
While exporting, a couple of cards from the Key 20th Anniversary set are giving errors as shown in the screenshots below. The ones that were affecting me specifically were Kch/W78-105 and Krw/W78-107. Removing them though appears to let the export process finish.

![image](https://user-images.githubusercontent.com/78577475/106984281-42686e80-6735-11eb-9cfd-ed46eccd6a86.png)

![image](https://user-images.githubusercontent.com/78577475/106984344-64fa8780-6735-11eb-8944-9f590f236250.png)

**Comment by ronelm2000** [comment]
I'll look into it. Can you get me a deck link of what you're working and what parse commands you used (if any)?

**Comment by ShoukakusHusband** [comment]
My apologies for the delay in my response.

I first parse the HotC translations of the Weiss-side promos and the Key set, in that order.

![image](https://user-images.githubusercontent.com/78577475/107110559-bfb7e000-6816-11eb-898b-939279f417a0.png)

![image](https://user-images.githubusercontent.com/78577475/107110571-ea099d80-6816-11eb-8109-e31fa027195a.png)

Then I try to export https://www.encoredecks.com/deck/JAQjGsFgD

![image](https://user-images.githubusercontent.com/78577475/107110597-22a97700-6817-11eb-93e6-fb0746eaaf8f.png)

**Comment by ShoukakusHusband** [comment]
(I realized that I probably shouldn't have cut out the end of the second parse)

![image](https://user-images.githubusercontent.com/78577475/107110623-613f3180-6817-11eb-88ac-323b0c046de2.png)

**Comment by ronelm2000** [comment]
Kch/W78-105 is also caused by YYT missing this particular serial somehow. Making DeckLog Post-Processor mandatory and YYT optional should fix this for the long-term future.
