### ISSUE TITLE
ERR] [Montage.Weiss.Tools.Impls.Parsers.Deck.DefaultDeckParser] Cannot find a compatible parser for this URL or File:

### ISSUE THREAD

**Issue by FunFragger** [ronelm2000/wsmtools#35]
Hi there, I am having issues entering the export URL and after hitting Enter getting this error message:

ERR] [Montage.Weiss.Tools.Impls.Parsers.Deck.DefaultDeckParser] Cannot find a compatible parser for this URL or File:

I am entering ./wstools export link as usual but it is not working. What can I do?

Thank you :)

**Comment by ronelm2000** [comment]
Hi, can you enter what command you were entering?

**Comment by FunFragger** [comment]
Hey :) for example: ./wstools export http://www.encoredecks.com/deck/igwr3tndF

**Comment by ronelm2000** [comment]
No update yet, I'm only about to start the sprint sometime between today and Sunday.

New changes are coming due to updates on EncoreDecks, so I may ask you to try again with a newer version and fresh `cards.db`, if it's okay with you.

**Comment by ronelm2000** [comment]
Apparently saying the word "fixes #35" closes it on issues itself, so do test it on GHA itself.

**Comment by MoeGuitarist** [comment]
I'm also experiencing the same error text, but specifically when attempting to export hotc translation pages (decks never cause this).
