### ISSUE TITLE
New Image Source for WS EN cards

### ISSUE THREAD

**Issue by ronelm2000** [ronelm2000/wsmtools#36]
Due to a recent announcement by JKTCG announcing its closure, this application will need to find a new image sources for Weiss Schawarz English cards. Any insight is welcome!

**Comment by DJDarkrai** [comment]
Would Strictly Broken TCG be willing to offer their images?

**Comment by ronelm2000** [comment]
> Would Strictly Broken TCG be willing to offer their images? Only issue would be older cards
I'd contact them, but based on the quality of new WSEN cards, I think only the old art cards would be the real issue.
