### ISSUE TITLE
recurring error

### ISSUE THREAD

**Issue by lekev262** [ronelm2000/wsmtools#37]
Hello,
I have a problem with the program
![image](https://user-images.githubusercontent.com/19492847/110207996-da698d00-7e86-11eb-8f51-e47c4147be23.png)

I manage to remove it by deleting the temporary file

just i tried to look at the code when i open the .sln i have an error
![image](https://user-images.githubusercontent.com/19492847/110208009-eb1a0300-7e86-11eb-9191-b94d10b76578.png)

To explain I downloaded the file as is and unable to open it there is a link statement which must be problematic

**Comment by ronelm2000** [comment]
> I manage to remove it by deleting the temporary file.
Due to the way .NET Core executables work, this is likely the only way to resolve "Missing assembly issues".
> just i tried to look at the code when i open the .sln i have an error
Can you explain what are you using to open the SLN file? You may require .NET Core 3.1 SDK depending on the version of VS, and/or it may not support the advanced functions like assembly trimming.

**Comment by lekev262** [comment]
> Can you explain what are you using to open the SLN file? You may require .NET Core 3.1 SDK depending on the version of VS, and/or it may not support the advanced functions like assembly trimming.

Basically he cannot open the SLN because it is impossible to open the Montage.Weiss.Tools.csproj and Montage.Weiss.Tools.Test.csproj

I don't know if it's me or the exporting files that is causing the problem? did anyone else manage to open the file before me?

then I will look for the opens in NET Core 3.1
I can't select the version at launch, but I'm afraid it won't open it with the NET Core 4 ...

**Comment by Akenaide** [comment]
Do you have a better fix ronelm2000 ? It's quite annoying to clean Temp files when it happen.

**Comment by ronelm2000** [comment]
I'm not sure if this is fixed, but .NET 5 changed the build process. This may need to be checked if it still persists. I cannot personally replicate this, except for very specific circumstances, I'll have to rely on everyone else to this.

**Comment by ronelm2000** [comment]
0.11.0 has been released which updates the .NET runtime to 6. I'm hoping that fixes this issue. If it doesn't contact me so that this can be re-opened.
