### ISSUE TITLE
Cannot Export HOTC Page

### ISSUE THREAD

**Issue by ronelm2000** [ronelm2000/wsmtools#45]
I'm also experiencing the same error text, but specifically when attempting to export hotc translation pages (decks never cause this).

_Originally posted by @MoeGuitarist in https://github.com/ronelm2000/wsmtools/issues/35#issuecomment-946744891_

Can you post the command you used for this?

**Comment by MoeGuitarist** [comment]
hi, sorry it took so long to reply. the parse command did resolve the problem. thanks for your time.

**Comment by ronelm2000** [comment]
Can you please copy/paste the entire log so that I can look into it?

To do this:
0. Perform the exact steps you did to reproduce the error.
1. Click on the "Windows PowerShell" title bar to select the window.
2. Click on the screen and "Select Windows PowerShell" should be the title of the title bar.
3. Drag the selection from the beginning of the command until the end (or when in doubt, just select everything).
4. Press Right-Click. That will copy the entire selection.
5. Paste it into [PasteBin](https://pastebin.com) or even here so that I can try to replicate the result and fix any error from it.
