### ISSUE TITLE
the tool doesn't start 

### ISSUE THREAD

**Issue by Slss0106** [ronelm2000/wsmtools#46]
when ever I start the powershell in the folder it just sits there doing nothing. the tool doesn't start and doesn't export or create the files needed
![wstools issue](https://user-images.githubusercontent.com/74620064/155337624-af859e8a-a53a-4e56-8469-0d91f9781412.png)

**Comment by Warliet** [comment]
There is no issue that the shell shows this.
Type the following stuff:
.\wstools.exe export [Encoredecks-Link/Decklog code]

If Translations are needed:
.\wstools.exe parse [HOTC Link]
and export again
