### ISSUE TITLE
linux artifacts in image output

### ISSUE THREAD

**Issue by namtsui** [ronelm2000/wsmtools#58]
Hi,
I'm on guixsd linux and get these artifacts in the output (see the end of this post).

https://github.com/namtsui/imagedump/blob/main/deck_ddm_12events_gate_pants_.jpg

First, I tried running the linux release and got a similar result. Then, I tried using mono to build from source (as in .github/workflows/nightly.yml). Both yielded the same results.

```
$ ldd wstools
        linux-vdso.so.1 (0x00007ffea5733000)
        libpthread.so.0 => /gnu/store/5h2w4qi9hk1qzzgi1w83220ydslinr4s-glibc-2.33/lib/libpthread.so.0 (0x00007f6dfd827000)
        libdl.so.2 => /gnu/store/5h2w4qi9hk1qzzgi1w83220ydslinr4s-glibc-2.33/lib/libdl.so.2 (0x00007f6dfd822000)
        libstdc++.so.6 => /gnu/store/6d0pl5khj08j3c2619jnypc8bznspgx8-gcc-10.3.0-lib/lib/libstdc++.so.6 (0x00007f6dfd64d000)
        libm.so.6 => /gnu/store/5h2w4qi9hk1qzzgi1w83220ydslinr4s-glibc-2.33/lib/libm.so.6 (0x00007f6dfd50c000)
        libgcc_s.so.1 => /gnu/store/6d0pl5khj08j3c2619jnypc8bznspgx8-gcc-10.3.0-lib/lib/libgcc_s.so.1 (0x00007f6dfd4f2000)
        libc.so.6 => /gnu/store/5h2w4qi9hk1qzzgi1w83220ydslinr4s-glibc-2.33/lib/libc.so.6 (0x00007f6dfd32e000)
        /gnu/store/5h2w4qi9hk1qzzgi1w83220ydslinr4s-glibc-2.33/lib/ld-linux-x86-64.so.2 (0x00007f6dfd870000)
namtsui@antelope ~/workspace/wsmtools_code/wsmtools/MontageWeissTools/bin/Release/net6.0$ file wstools
wstools: ELF 64-bit LSB pie executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /gnu/store/5h2w4qi9hk1qzzgi1w83220ydslinr4s-glibc-2.33/lib/ld-linux-x86-64.so.2, BuildID[sha1]=38f32dad6bd760faf250dafce41a819685ce9c84, for GNU/Linux 2.6.32, stripped
```

To build I used:
```
dotnet restore
dotnet build --configuration Release --no-restore
```

Then, I ran the binary from wsmtools/MontageWeissTools/bin/Release/net6.0
$ ./wstools export https://www.encoredecks.com/deck/G17icr9vk

Finally, logs follow. When building a DDM deck (https://www.encoredecks.com/deck/G17icr9yk) it gets the image with artifacts (https://github.com/namtsui/imagedump/blob/main/deck_ddm_12events_gate_pants_.jpg). When trying to build a DAL deck (https://www.encoredecks.com/deck/BhJy3HOn4) it exposes a crash with image 10 in zlib.

[log_dal.txt](https://github.com/ronelm2000/wsmtools/files/10088993/log_dal.txt)
[log_ddm.txt](https://github.com/ronelm2000/wsmtools/files/10088994/log_ddm.txt)

**Comment by ronelm2000** [comment]
I'll need help to test this as image artifacts will be hard to make unit tests for. Thanks and I'll see if this is an issue with ImageSharp library, and if yes, how to make a reproducible error.

**Comment by namtsui** [comment]
nice lead. upgrading ImageSharp 1.0.3 --> 2.1.3 in Montage.Weiss.Tools.csproj seems to have resolved the issue.

https://github.com/namtsui/imagedump/blob/main/deck_dal_choice_standby.jpg

https://github.com/namtsui/imagedump/blob/main/deck_ddm_12events_gate_pants_good.jpg

see: https://github.com/SixLabors/ImageSharp/issues/1014

**Comment by ronelm2000** [comment]
You can check if there's any issues via the newest nightly in GitHub Actions.

**Comment by namtsui** [comment]
The binary works with two more decks on linux. I'll have to wait until distro updates to .NET 7 yet to test out building from source. Thanks for the fix.

As an aside,  decks with parenthesis in the title seem to trip up the program because in tts it throws unsupported image format (*.jpg...). It doesn't seem like a big deal though because I renamed the deck to remove parentheses and it works.

problematic: 8SB Nino 5HY EN (update) https://www.encoredecks.com/deck/y2RI_FnVG
ok: 8SB Nino 5HY EN https://www.encoredecks.com/deck/oZOk8gBFP
