### ISSUE TITLE
Unable to parse translations of some sets from HOTC

### ISSUE THREAD

**Issue by Patchoulidaze** [ronelm2000/wsmtools#6]
wstools cant parse translation from sets like kancolle 5th fleet and bang dream

**Comment by ronelm2000** [comment]
Please check in with the latest wstools build on https://github.com/ronelm2000/wsmtools/actions/runs/86409598 then delete cards.db and see if that fixes your issue.

**Comment by Patchoulidaze** [comment]
Hi thanks, it works kinda, also it seems that saekano set one doesn't get parsed even though there's no errors
