### ISSUE TITLE
Partially translated sets blocking EncoreDecks export

### ISSUE THREAD

**Issue by alyucia** [ronelm2000/wsmtools#69]
Hi, I 've been trying to export some JP Shinymas decks to use in TTS but I was running into some problems.
I did some looking into the code and I think I found the problem.

Shinymas currently consists of  two sets (ISC/S110 and ISC/S81), while neither set has a proper English translation, when parsed from both sets have full (unofficial) English effect text.

S110 has no EN names, so when parsed it has JP names in both EN and JP columns.
https://i.imgur.com/AHjHeH2.png
These cards work properly and are treated as fully translated cards. (even though they're not)

However, for S81 EncoreDecks has placeholder names for some trial deck cards.
https://i.imgur.com/nL26ChJ.png

When not using any of these cards and only using cards with null EN names, the set is treated as an untranslated set, and I am given the option to export with JP names. The exported deck works properly.
https://i.imgur.com/ArBkJiZ.png

However, if there is a mix of placeholder names and EN names, the set is treated as broken and missing some translations, and the process ends with no option of export.
https://i.imgur.com/H4jVJHV.png

Is there any way to force the process to use JP names in this situation, instead of ending the process?
Or a way to delete the placeholder names from the db, so that the set is always treated as an untranslated set?

**Comment by ronelm2000** [comment]
Will work on this, but you can try to force the S81 to have English translations by using HOTC translations as a workaround.

**Comment by alyucia** [comment]
> Will work on this, but you can try to force the S81 to have English translations by using HOTC translations as a workaround.

Is there a command to do this? I'm using >wstools fetch S81 but it's defaulting to encoredecks and doesn't seem to have an option for HOTC

**Comment by ronelm2000** [comment]
> > Will work on this, but you can try to force the S81 to have English translations by using HOTC translations as a workaround.
> 
> Is there a command to do this? I'm using >wstools fetch S81 but it's defaulting to encoredecks and doesn't seem to have an option for HOTC export --parser also doesn't seem to support hotc, it only has encoredecks under possible values.

You need the url for the HOTC set files:
```powershell
./wstools parse https://heartofthecards.com/translations/idolmaster_shiny_colors_trial_deck.html
./wstools parse https://heartofthecards.com/translations/idolmaster_shiny_colors_booster_pack.html
```

**Comment by ronelm2000** [comment]
PS: when checking with GHA's nightly build, delete `cards.db` first before retrying since that is necessary for the new logic to work properly.
