### ISSUE TITLE
Image Ratio isn't correct

### ISSUE THREAD

**Issue by KuroViLolitannia** [ronelm2000/wsmtools#7]
![image](https://user-images.githubusercontent.com/55943306/80904097-c623a380-8d3c-11ea-9261-ef7ea0ae2fdf.png)

One of the image doesn't show up and when I try to add it via link (from Encoredecks and Littleakiba, I tried both) it says image ratio isn't correct. Did I do something wrong? Thank you!

**Comment by ronelm2000** [comment]
Can you try the latest build [here](https://github.com/ronelm2000/wsmtools/actions/runs/86409598) and see if the issue persists? This was reported around a week ago via other sources and I've built a fix for it, but none of the original reporters have confirmed the fix.

**Comment by ronelm2000** [comment]
Should be fixed properly in v0.2.1
