### ISSUE TITLE
Microsoft.DotNet.PlatformAbstractions

### ISSUE THREAD

**Issue by TravisJEngle** [ronelm2000/wsmtools#9]
Started getting this error the other day, unsure what could be done to solve it
Error:
  An assembly specified in the application dependencies manifest (wstools.deps.json) was not found:
    package: 'Microsoft.DotNet.PlatformAbstractions', version: '3.1.3'
    path: 'lib/netstandard2.0/Microsoft.DotNet.PlatformAbstractions.dll'

**Comment by ronelm2000** [comment]
Odd error. What's your VS version? Here's mine.
![image](https://user-images.githubusercontent.com/12634987/85810690-82727680-b78e-11ea-8a5c-ed5127146e02.png)

**Comment by TravisJEngle** [comment]
This is what my system is running, but I've never had this issue running through command prompt until now
![image](https://user-images.githubusercontent.com/8657999/85812253-2415ab80-b72e-11ea-9fdd-96d83e029ee5.png)

**Comment by TravisJEngle** [comment]
Of note, the program operates through command prompt just fine on a different computer of mine, so I have zero clue why that dependency is missing all of a sudden

**Comment by ronelm2000** [comment]
It's very likely because you're using VS2017. wstools uses .NET Standard 3.1. And afaik VS2017 only supports until .NET Standard 2.0. I'm planning on adding this on documentation so I'll keep this bug open for now.

![image](https://user-images.githubusercontent.com/12634987/85812858-6245b600-b794-11ea-84b4-fb3020947c27.png)

**Comment by ronelm2000** [comment]
Update:
Documented as fixed by installing .NET Core 3.1 SDK after contact via Discord; no need to install VS2019. But Installing VS2019 (and higher) is still recommended.
